### ISSUE TITLE
Convert phone numbers to specific QR-code (Scan-to-call feature)

### ISSUE THREAD

**Issue by fewrainbows** [igorlogius/selection-to-qrcode#1]
Hello!

Awesome addon!

A request for you, I think it would be a "killer feature".
None of the mozilla plugins i found have this!

AIM: I'd like to call telephone numbers I see on my screen with my mobile.
Right click on a telephone number could be ported to a phone number specific qrcode.

Scan-to-call!

What do you think?

Thanks for your job

**Comment by igorlogius** [comment]
Seems like adding this might be relatively easy.
But the issue is how to expose this feature in a userfriendly way. 

Analysing the Selected content is already an issue, since Phone number can container some uncanny symbols `+`, `(`, `)`, `:space:`  
Maybe instead of pre-analysing the data ... it would be better to just add another menu entry ... and let the user decide if it is a phone number ... might be smarter


```
BEGIN:VCARD
VERSION:2.1
N:
TEL:(+49) 0121212312
END:VCARD
```
ref. https://en.wikipedia.org/wiki/VCard

Phone number RegEx  `^[+]*[(]{0,1}[0-9]{1,4}[)]{0,1}[-\s\./0-9]*$`

**Comment by fewrainbows** [comment]
Hello Igor!

Thank you for your reply!!!

> Analysing the Selected content is already an issue, since Phone number can container some uncanny symbols `+`, `(`, `)`, `:space:` Maybe instead of pre-analysing the data ... it would be better to just add another menu entry ... and let the user decide if it is a phone number ... might be smarter

Very good: it might work!!


It might be a second stage, or more "advanced solution" ..check this out!
Just to share a thought
https://addons.mozilla.org/lt/firefox/addon/phone-number-beautifier/
That plugin already detects phone numbers, thay have more options...since the mindset is to send the number to a headset or similar.
One option might be "create phone number QR code"

Then every potentially dialable number is identified and labelled on the page..

Thanks for your time

**Comment by igorlogius** [comment]
> One option might be "create phone number QR code"

i think i will go with this and only show the `Create Contact QRCode` option
when the selected content matches the regular expression  
`/(\b|^\d|\+|\()(\+?\d{1,3}\s?)?(\d{1}[\s.-]?)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}\b/gi`
(taken from phone-number-beautifier) 

If the regex turns out to be not good enough ... 
i guess i'll improve or replace it with something else later.

**Comment by fewrainbows** [comment]
Very good!!

I think the best option for a quick "Scan-to-call" is not a VCard QR code..

But a phone number.. as example from https://www.qrcode-monkey.com/#phone

![immagine](https://user-images.githubusercontent.com/88545208/153585588-4525b139-5db1-4e2d-8e08-f46115be7e07.png)

Thanks

**Comment by fewrainbows** [comment]
Another thing....

I noticed I quoted you just 1 firefox plugin.
And you already catched a "good way"!

As a reference or a "shared thought" I'd like to link you this as well:
https://addons.mozilla.org/it/firefox/addon/telephone-number-detection/

**Comment by igorlogius** [comment]
Some Refs. 
- https://github.com/zxing/zxing/wiki/Barcode-Contents
- https://stackoverflow.com/questions/19900835/qr-code-possible-data-types-or-standards

**Comment by igorlogius** [comment]
Done with `v1.1.0`  ... might need some refinement ...and UI/X improvement ... but lets try and keep these issues atomic ... otherwise it gets hard for me to work on them.

**Comment by fewrainbows** [comment]
BOOOM!

look awesome

start betatesting : )
Thank you
